### ISSUE TITLE
Feature Request: Hdmi Pass through

### ISSUE THREAD

**Issue by Muirson** [hd-zero/hdzero-goggle#114]
Hdmi passthrough will be good for people using external input devices such as the walksnail system for others to spectate or record on a dvr.

**Comment by LeanderVanhulle** [comment]
This feature is currently stated in the official manual and thus might be stated as a bug as this isn't working.
This is stated on page 7: 

![image](https://user-images.githubusercontent.com/33485374/236647617-76e80305-d3c3-4147-b43b-769cd78b5a65.png)
