### ISSUE TITLE
Feature request: Support timestamp in DVR metadata

### ISSUE THREAD

**Issue by Wikiwix** [hd-zero/hdzero-goggle#116]
As discussed by @rquellet in [this YouTube video](https://www.youtube.com/watch?v=p4qXiQrtCkU&t=443s) there is a RTC in the goggles.
Having this information in the DVR files is essential for me and allows easier management of flight footage.

See #123 for details on implementation.

**Comment by razzeee** [comment]
related to https://github.com/hd-zero/hdzero-goggle/issues/42

**Comment by evilC** [comment]
Out of curiosity, the video says there is a connector, but it's not too clear exactly what the connector is.
Is it a cell holder? ie can we just pop a battery in there, or is it a separate cell holder and what is on the PCB is just a pin header to connect the cell holder?

**Comment by Wikiwix** [comment]
@evilC Ryan points at the connector. Looks like some JST connector.
If you google "*RTC battery*" , you will find examples of CR3032 with a plug. All I saw seemed to use the same connector so I guess this is kind of *the standard*.

**Comment by Master92** [comment]
Isn't this feature implemented? Maybe you should consider closing this and related issues that have been implemented by now 😉

**Comment by Wikiwix** [comment]
@Master92 This particular one is not fully implemented AFAIK (though I am still on 9.0). The file gets creation and edit timestamps, but the mp4 does not get the typical metadata yet.
See [this comment](https://github.com/hd-zero/hdzero-goggle/issues/123#issuecomment-1484204361) for some research I did a while ago.
Closed the other issue I created as completed though.

**Comment by Master92** [comment]
Oh okay maybe I've mistaken the file creation date - which is set - for the video metadata.
I'll have a look at that when I've got some time. Your approach seems promising and I'll update as soon as I've come around to trying it out.
