### ISSUE TITLE
Feature Request: Confirmation of flashing VTX

### ISSUE THREAD

**Issue by RustyPaint** [hd-zero/hdzero-goggle#127]
The flashing to a VTX via the firmware menu happens so fast, it is hard to tell if it has completed or not.  It would be nice to have a confirmation message saying that the firmware flash has completed successfully.

**Comment by bkleiner** [comment]
Would blocking user input and continuing to display the message for <n> amount of time be satisfying the need here?

**Comment by bkleiner** [comment]
PR implementing this delay https://github.com/hd-zero/hdzero-goggle/pull/129 
you can find a update file to try it here https://github.com/hd-zero/hdzero-goggle/actions/runs/4029903958 (the `.bin` file)
please leave further feedback directly in the PR linked above.
