### ISSUE TITLE
Feature request: Go straight to camera view on power up of goggles when "Last" mode is enabled

### ISSUE THREAD

**Issue by evilC** [hd-zero/hdzero-goggle#139]
Given `Auto Scan` is set to `Last`  
When I power up the goggles
Then it should not waste time loading and showing the menu before going to the camera view

Is this unavoidable? ie is it wasting any time by loading the menu? Can  we get a camera feed quicker by not loading / showing the menu?

**Comment by bkleiner** [comment]
The menu is displayed while the divimath chips go through there "training sequence".
That is not avoidable and the scan screen is used as a loading screen of sorts.
i don't see how we can get rid off it without completely, as we need to display _something_ until the video is ready.

**Comment by evilC** [comment]
If it's unavoidable, IMHO if we can, it would be better to leave it on the logo screen until the UI is ready for user interaction - as at least that has a waiting animation

**Comment by bkleiner** [comment]
that would basically be #140, i have something along those lines in underway already ("loading screen" until the app is fully ready)

**Comment by evilC** [comment]
OK, I'll close this one then
