### ISSUE TITLE
OLED Screensaver Enhancement to avoid OLED burn in

### ISSUE THREAD

**Issue by FPVRishi** [hd-zero/hdzero-goggle#190]
1) Can we have an option to have a manually selectable screensaver, which comes on if:
a) there is no change in image on the screens for a particular time (which can be set by the user) and
b) if the screen is displaying the main menu for a particular time (which can be set by the user).

(Alternatively, this could be based on no movement of the goggles, using the headtracker sensor, but there should be the option to set this for 5 minutes or whatever is a 'regular' flight time/user definable time as some people may fly whilst keeping very still)

**2) Also, could the the goggle image also be made to move 10 pixel/minute, following the order: middle→right→middle→left→middle, circulating? This may help keep the OLED panels better protected even when the goggles are being 'used' in menu and in flight. Again, this could be user adjustable to be on or off throughout, or only whilst in the menus, or only whilst flying, or just totally off?**

**3) Finally, could this functionality be extended to apply not just in HDZERO source mode, but also in HDMI IN source mode (for those of us who also use a Walksnail VRX) and also perhaps in EXPANSION MODULE mode, for those of us who fly analogue? _(The enhancement requests may automatically work across all input sources, but I don't know how it would work, hence I am trying to be explicit in my requests_)**

Not sure how best to implement, but I know Skyzone have these features on their 03o goggles (and maybe even a better solution for their 04x): 

"OLED Sleep
The sleep mode can be set in the menu( 1minute 3minutes 5 minutes）, default is 3 minutes.
When sleep mode is activated, the goggles will detect the movement of the goggles (via head tracker sensor), when the goggles stay still to the present time, the goggles will switch to sleep mode, the  OLED screen will turn off when the sensor detects the movement of goggles, the goggles will quit sleep mode.
The sleep mode only turn off the OLED to save the lifetime, the rest functions of goggles is still working (receiver,DVR etc).
OLED Screensaver
The image will move 10 pixel/minute, flow the order: middle→right→middle→left→middle, circulating.
This function can’t turn off.
Read more: https://manuals.plus/skyzone/fpv-goggle-kit-manual#ixzz7vDRxbwRI"

**Comment by ligenxxxx** [comment]
We have add **Go sleep!** at menu.
