### ISSUE TITLE
HD OSD stays on screen after switching from HDZero to Analog

### ISSUE THREAD

**Issue by Proskate** [hd-zero/hdzero-goggle#194]
After flying/spectating HDZero and switching to analog expansion module OSD from HDZero stays on screen, need to restart goggles to get rid of it. Don't know if this exists with other inputs, may try soon with HDMI. 

Nothing big, but it was a little bit annoying at the competiton when spectating hdzero and later flying analog or even switching between systems to spectate

**Comment by bkleiner** [comment]
fix is merged https://github.com/hd-zero/hdzero-goggle/pull/177
