### ISSUE TITLE
Where are the CAD files?

### ISSUE THREAD

**Issue by jhoblitt** [hd-zero/hdzero-goggle#198]
The [manual](https://www.hd-zero.com/_files/ugd/967e02_842232ff9a4a4ecfa41dd7b45b973283.pdf ) has this blurb:

> The HDZero Goggle is open source. You can find the SoC Firmware and Goggle CAD files at
> [Github](https://github.com/hd-zero/hdzero-goggle).

There doesn't appear to be anything like STEP files in this repo.  It would be appreciated if there was a pointer to the CAD files in the README.

**Comment by rquellet** [comment]
https://github.com/hd-zero/hdzero-tooling
