### ISSUE TITLE
Goggle DVR scaling between 720p/1080p

### ISSUE THREAD

**Issue by burnitdn** [hd-zero/hdzero-goggle#208]
ISSUE:
DVR scales/crops the output of the screen when recording after switching resolution modes between 720p and 1080p
![1080-720 switch](https://user-images.githubusercontent.com/125995456/230474681-1f0145a7-8fd8-459f-8519-3f89304c64b7.png)
![720-1080 switch](https://user-images.githubusercontent.com/125995456/230474683-bc299043-e031-47f7-9568-b4a881086e81.png)

TO REPRODUCE:
Goggles and vtx using rev04042023 firmware
Set goggles to record manually with .ts format

Power goggles/aircraft, enter camera menu, switch aspect ratio from 16:9full to 1080p30 (or vise versa), save and exit menu, manually start recording on goggles, manually stop recording. Resulting DVR file will be scaled/cropped up or down depending on which way the aspect ratio was switched.

**Comment by ligenxxxx** [comment]
solved.
