### ISSUE TITLE
Feature Request: add "race mode" for screen FOV? (and goggle OSD change request)

### ISSUE THREAD

**Issue by poastoast** [hd-zero/hdzero-goggle#218]
As HDZero gets more popular with racing, I think it'd be nice to see a feature similar to Orqas where you can choose to reduce the FOV to 33-37°. And it gives an option for those who don't always want an absolutely massive screen size (or that's just a me thing).

And as a feedback thing, I feel itmd be better if the the goggle antenna rssi indicators should be reordered so from left to right, it'd be:
side left, top left, top right, then side right
It kind of feels backwards seeing that signals 1 and 4 ad the inner 2 SMAs and 2 and 3 are the outer 2 SMAs

**Comment by ligenxxxx** [comment]
HDZero Goggle cannot support this.
