### ISSUE TITLE
GoSleep! UX improvements

### ISSUE THREAD

**Issue by robhaswell** [hd-zero/hdzero-goggle#223]
Even with the new update, the boot time is very high. This can lead to you holding up a race if you forget to turn them on.

It might be possible to reduce power consumption to the point where the units don't need to be powered down. I suggest that a mode could be activated (by way of some button press, perhaps both buttons at once) to enter "standby mode".

In standby mode, the HDZero radios and OLED as powered down, and there could be additional firmware actions which reduce power consumption of the MCU. Fans are disabled or run at minimum. Standby mode ends as soon as any button is pressed.

Standby mode could also be entered automatically after a period of no signal, similar to the current OLED-off function.

---

## Edit

Since this issue was created, a new function "GoSleep!" has been added to the menu. I've updated this issue to represent my suggestions for UX changes to GoSleep! See comment https://github.com/hd-zero/hdzero-goggle/issues/223#issuecomment-1598843309

**Comment by pitts-mo** [comment]
@robhaswell a Go Sleep! function recently added and I have submit PR #268 with some improvements.

In your view of Standby mode... should the goggle attempt to immediately return to Live view on resume? or would you prefer it to return to the menu with "Go Sleep!" still highlighted?

Anyone else wish to weight in?
Thank you,
-p

**Comment by pitts-mo** [comment]
As of 9.1.0-rc2 the Go Sleep! function appears to provide the basic hardware sleep functionality needed to resolve this issue. However, performance and usability are lacking.

Outstanding items I see are:
-make Go Sleep! function independent of menu.
-add logic for corded long left + right button press to actuate Go Sleep! function.

Sound correct?
If so maybe @robhaswell can update the title for this issue in a few days?

**Comment by SAMUD** [comment]
I updated my googles to the lastet version and the GoSleep is cool. However some quick acess for this is needed.
Either both buttons or some kind of double click on the rec-button to send them to sleep.

Optional I think something like one beep every 30sec like on Orqa googles would be cool, so you are reminded that the googles are still powered on.
