### ISSUE TITLE
Feature Request: add stereoscopic 3D support

### ISSUE THREAD

**Issue by pitts-mo** [hd-zero/hdzero-goggle#231]
The HDZero goggle appears to be physically capable of displaying several stereoscopic 3D modes.

Suggest starting with SideBySide mode from HDMI input.

**Comment by pitts-mo** [comment]
Can the HDZero receivers be split in order to display one RF channel on each screen?

**Comment by lebed2045** [comment]
wow, that would be sick! also good for the company, so you can sell two vtx for the drone.

**Comment by wernight** [comment]
Given how much "simple" VR headset make a buzz, having HDZero Google work as VR headset would actually up the value. They may not need to be great at it, just... good enough.

**Comment by WooD1k** [comment]
It would be great to have a feature like this!

**Comment by ewindisch** [comment]
This would be exciting for multiple use-cases. 3D FPV will soon be possible from a single VTX and camera using AI estimation with higher latency and/or reduced framerate, reducing weight and cost to these configurations.

**Comment by ligenxxxx** [comment]
This will not be possible due to hardware limitations.

**Comment by konanast** [comment]
I was wondering if there is any information available regarding potential support for stereoscopic 3D in the new HDZero 2 goggles?

Is this feature being considered, or there is still technical limitation that would prevent it?
