### ISSUE TITLE
DVR: Record HDMI Source

### ISSUE THREAD

**Issue by shannonbaker** [hd-zero/hdzero-goggle#26]
When using a HDMI source it would be helpful to record this input.  This is useful for keeping DVR recordings in a single spot when used with complementary VRXs such as the WS VRX.

Suggest minimal goggle OSD whist the recording happens (record, goggle temp warning and goggle battery warning) with goggle OSD not recorded.

**Comment by bkleiner** [comment]
we gonna need some input from divimath on this one.

**Comment by CrazyDoge128** [comment]
That would be a great feature. I was thinking of it when i got my ws vrx.

**Comment by robhaswell** [comment]
I'm convinced that my goggles used to record HDMI DVR on a previous firmware, but they don't at the moment.

**Comment by ligenxxxx** [comment]
Due to copyright issues, we will not add this feature.
