### ISSUE TITLE
9.1.0 Randomly reboot itself (Not a power issue)

### ISSUE THREAD

**Issue by asyncnomi** [hd-zero/hdzero-goggle#280]
1. I initially was on 9.0.27, 

    > there already was a bug that cause the goggle to reboot (and failed, stuck at hdzero logo) when unplugging a drone streaming hdzero to the goggle, the complete loss caused the goggle to reboot. 

    > Not a single issue with analog (i was able to let the goggle on for 1hour and more). 

    > A workaround was to quickly switch to the main menu after unplugging the drone

2. I flashed the last 9.1.0-rc1 fw on my goggle, 

    > now the goggle are randomly rebooting while i'm flying.

**Comment by pitts-mo** [comment]
Hmm... 
There is 9.1.0-rc2 with RX 73 update you could try.

I am awaiting my first HDZero VTX. But, gut tells me to try stripping goggle down to essentials. example: HDZero mode without analog module, SD card or any other items connected to the power system while using the stock power cable and a normal battery (not regulated/smart).

**Comment by pitts-mo** [comment]
Hello @asyncnomi , Has this issue been resolved?

**Comment by asyncnomi** [comment]
Ok this turns out to be a hardware issue !
Any crossfire/elrs link can interfere with the board causing the reboot of the goggle.
Bringing the radio clause enough to the head has been classified has rare occurence by the hardware team, and thus no shielding is present on the power board.
That explains the reboot when unplugging the battery (where I bring my head down near the crsf antenna), and in flight reboot when I'm sit down with the rc in my hand near my head.
This issue seems to concern almost everyone so we just need to be careful about it
