### ISSUE TITLE
Indicate version strings of boundled bin files within notes for each release.

### ISSUE THREAD

**Issue by pitts-mo** [hd-zero/hdzero-goggle#302]
There has been re-occurring struggle for users to know what download versions should include resolution for specific analog or digital rx bugs. I suggest every release notes indicate the version strings for the supporting bin files bundled within. 

Can this be automated?

9.1.0 example:
~~HDZero Receiver version~~ rx: 73
~~Analog Decoder version~~ va: 184

Is there any benefit to display:
boot version?
OS version? 

Update: I have been informed my understanding of the service of rx and va firmwares was incorrect and incomplete. So a better user description would be required.

Maybe these example descriptions would work?
5680 chip, Digital Signal Decode firmware rx: 73
FPGA chip, Analog and digital signal processing firmware va: 184

**Comment by ligenxxxx** [comment]
sloved
