### ISSUE TITLE
[Feature Request] Add ext4 and exFat file system support 

### ISSUE THREAD

**Issue by antony-weber** [hd-zero/hdzero-goggle#307]
Add ext4 and exFat sd card file system support

**Comment by christhomas** [comment]
Apparently the Tina Linux source tree doesn't contain the code for these file systems. But I think that's just a case of adding it, compiling it, and trying ti out. Just adding this information here because I was told it in a different issue

**Comment by antony-weber** [comment]
Ext4 exist in Tina Linux source tree

**Comment by christhomas** [comment]
Ah, yeah sorry, you’re right, I should have only mentioned exfat

**Comment by zandorsp** [comment]
I think F2FS filesystem [https://en.wikipedia.org/wiki/F2FS](url) is a better option, because it's optimized for SD, transparent compression and atomic operations.

**Comment by christhomas** [comment]
mountable in windows and macos without any drivers to be installed?
