### ISSUE TITLE
[feature request]AI corrected signal loss.

### ISSUE THREAD

**Issue by Shaun-York** [hd-zero/hdzero-goggle#311]
Would it be possible to train a computer vision model with OpenCV to fill in lost image data in realtime?

**Comment by nurikk** [comment]
And AI 4k upscale 😍

**Comment by robhaswell** [comment]
You would need to add a GPU into the video path. I'm certain this would be a fun research project but there is no chance of seeing this come included with HDZero.

**Comment by lebed2045** [comment]
jokes aside, it seems possible to pre-train model to predict the most statistically optimal pixel color based on neighbours so actual pixel filaments can be done on fly with very low computation overhead. Another option, but I'm sure developers explored it already, is to dedicate small part of bandwidth to send colors of big areas first, i.e. like old JPEGs use progressive loading in the past.

**Comment by xtr0d3m0n** [comment]
Depending on how much hardware u got on v536. It got an NPU that can probably do some decent inference.

**Comment by francoisbeaussier** [comment]
Would  averaging the neighbouring pixels already be an improvement over the current "multicolour static" behaviour?

**Comment by ligenxxxx** [comment]
Any software-based video processing will increase latency.
