### ISSUE TITLE
Why doesn't the goggles support higher capacity sdcards?

### ISSUE THREAD

**Issue by christhomas** [hd-zero/hdzero-goggle#315]
Is there a hardware reason why I can't use a 256GB sdcard in these goggles? If I plug in a 8GB card it works. But a 256GB card it doesn't.

Yet linux supports it no problem. So I'm assuming it's a hardware issue.

**Comment by pitts-mo** [comment]
I do not completely understand the issues people have had with SD cards. 

PR#306 might help you once it is released.
For now you could try reformatting your card using sdcard.org tools or maybe re-run the full five file goggle update from Rev_26062023.
good luck,
-p


More Info (working with SD cards can get messy):
I have been using a SanDisk High Endurance 256gb micro SD card (U3 XC1 V30 C10) without issue on my batch 2 goggle. I accumulate generously more than 32gb of DVR storage during a session. Even with HDZGOGGLE builds running from SD and running firmware updates for Goggle and VTX I have not had any issues.

However, I always verify cards are partitioned and formatted fat32 to the sdcard.org standards using gnome-disk-utility. In my experience most SD cards do not come per-partitioned and formatted to sdcard.org standards nor do most operating systems re-format to sdcard.org standards.

Additional Note:
I have seen people reference a 32GB limit and even people reporting larger cards worked but would not record additional DVR after reaching 32GB of card usage.

**Comment by christhomas** [comment]
This is a good point, it's straight out of the box and into the goggles, so it seems like the problem is the operating system is only checking the device is mounted, not existing. If you check the device is mounted, then surely it's because it's the right format and can be mounted. But what about cards formatted with exfat, then it's inserted, it could be reformatted, but it can't be mounted because the goggles doesn't support exfat. 

So #306 looks like it would fix that. 

An improved solution would be #306 in combination with the ability to read exfat straight away. Linux already supports exfat. So this is probably just a driver issue as maybe the kernel is not compiled with the driver. I'm just starting with hdzero and I've got decades of experience with linux. So I'm working up the list of things to learn and get right and then I might start taking a stab at these smaller issues. Cause it seems like I could be useful here.

But anyway, just gotta wait for that pull request to merge. Thanks for the help

**Comment by antony-weber** [comment]
@christhomas 
Unfortunatly there is no exfat support in Tina Linux sources. I allready build kernel modules and file system tools for ext4 file sysytem. I will test them when I have more free time. For linux users it will be a good solution.
Although Tina Linux is based on OpenWRT and OpenWRT has exfat support. So it will be not so dificult to get exfat suppport for our googles. The mailn question is whether the googles have enough space for all this features.
