### ISSUE TITLE
Is 50°C really too hot for the top chip ?

### ISSUE THREAD

**Issue by rcmz** [hd-zero/hdzero-goggle#324]
Hello, I'm changing the fans on the goggle to make them quieter
![image](https://github.com/hd-zero/hdzero-goggle/assets/40456553/cbe49b32-bafc-4f3b-8fb9-23e9b99062db)
I noticed that the maximum temperature allowed for the top chip is only 50°C
This seems really low, for example the side chips are allowed to go up to 85°C
![Screenshot from 2023-07-31 18-01-38](https://github.com/hd-zero/hdzero-goggle/assets/40456553/61230523-60d4-432b-a3b7-6e8e83eb9f90)
The chip in question, the GW2A-LV55 FPGA is rated to go up to 85°C
![Screenshot from 2023-07-31 18-05-18](https://github.com/hd-zero/hdzero-goggle/assets/40456553/37912ebb-beae-472d-b355-83c1eeb9ab87)
And the other top chip, the V536-H is rated for 115°C
![Screenshot from 2023-07-31 18-06-42](https://github.com/hd-zero/hdzero-goggle/assets/40456553/d2a26e9e-5566-42d5-bb09-c68edabeb3a4)
So why mark 50°C as a risk ? Isn't it safe to let it go a bit hotter ?

**Comment by ligenxxxx** [comment]
This is not the case. Higher temperatures can affect the stability of some high-speed signals.
