### ISSUE TITLE
Manual channel selection screen with scanner

### ISSUE THREAD

**Issue by aviphysics** [hd-zero/hdzero-goggle#325]
If it isn't too much effort, could someone add a manual HDZero channel selection screen with the band scanner display from the scan screen?

This would make it easier to see which channels are in use and find other HDZero signals.

**Comment by pitts-mo** [comment]
Isn't this already the default behavior?

However, I would like the ability to see general RF usage across the band (spectrum analyzer view), show the HDZero channels at their approximate placements within the band,  show if HDZero signal is detected in those channels, and still allow selecting from HDZero channels that do not already show an HDZero signal was detected.

**Comment by aviphysics** [comment]
> Isn't this already the default behavior?
> 
> However, I would like the ability to see general RF usage across the band (spectrum analyzer view), show the HDZero channels at their approximate placements within the band, show if HDZero signal is detected in those channels, and still allow selecting from HDZero channels that do not already show an HDZero signal was detected.

The current behavior is that it will scan and select the first HDZero signal it detects.

**Comment by pitts-mo** [comment]
Oh, my mistake, I only have one HDZero VTX to test with. But the scan now page hint implies it scans for all signals and would allow you to select from all active HDZero channels (if more than one is detected).

**Comment by ligenxxxx** [comment]
This is a repeat of #1
