### ISSUE TITLE
Automatic download&update goggle/vtx fw from github via wifi client

### ISSUE THREAD

**Issue by ligenxxxx** [hd-zero/hdzero-goggle#330]

**Comment by SumolX** [comment]
Refer to branch https://github.com/SumolX/hdzero-goggle/tree/online_update

Downloader portion completed, next is integrating downloader with goggle application.

**Comment by SumolX** [comment]
PR has been submitted:  https://github.com/hd-zero/hdzero-goggle/pull/334

**Comment by Master92** [comment]
#346 has been merged. This issue can be closed 👍
