### ISSUE TITLE
Feature Request : Record HDMI with Audio from Mic or Line In

### ISSUE THREAD

**Issue by Yith1** [hd-zero/hdzero-goggle#344]
I love the Mic In/Line In Audio recording I get with the goggles when flying with HDZero.

I've been playing with the Walksnail VRX with the goggles, for fixed wing planes where latency is less of an issue, and the gyro stabilised on-board recordings whilst being very clear, just are not the same... there's no audio! No chatter between the pilot and those around him. No sound as the plane whooshes past above.

Would it be possible to have the goggles be able to record the HDMI in to the SD card mixed with the Mic and/or Line In audio mixed in? Then this audio could be mixed in easily with on-board recording if desired, etc... Otherwise I'm going to have to look at getting a secondary audio recording device.

**Comment by ligenxxxx** [comment]
HDZero Goggle cannot record or listen to audio from HDMI.

**Comment by Yith1** [comment]
@ligenxxxx 

No... please mix the audio from "line in" into the feed from hdmi in and record that.

This is so that a commentary can be recorded when using an external rx module (eg. Walksnail).
