### ISSUE TITLE
Supporting separate inputs for each eye to enable stereoscopic 3D effect

### ISSUE THREAD

**Issue by hfan** [hd-zero/hdzero-goggle#396]
I'm curious if it's possible at all to support 2 separate FPV RF channels as inputs to the displays for each of the eyes. Some older Skyzone goggles support that for analog (e.g. Skyzone 02S V+), but with much smaller FOV and lower resolution, also no OLED.

Admittedly, stereoscopic 3D view is effective only in close range, but for indoor whoops that might be actually a fun experience.

For now, I'm curious to support such a setup in analog, what kind of hardware mod is necessarily, like in the hardware, whether is it possible to drive the 2 displays separately and how to feed the AV signals in from 2 separate VRX.

**Comment by ligenxxxx** [comment]
HDZero Goggle's left and right OLEDs can only display the same source physically. So what you said doesn't work.
