### ISSUE TITLE
Feature request: Interpolate missing pixel data from neighboring pixels

### ISSUE THREAD

**Issue by AlexandreBonneau** [hd-zero/hdzero-goggle#40]
Instead of showing random pixel data when there are missing info, make an interpolation from the neighboring pixels (or even from the previous frames).

I assume this could take more CPU power, and hence time, so this feature should be togglable in the settings.

**Comment by bkleiner** [comment]
This is really outside of the scope of _this_ repository, as the image is received and process by a asic & fpga.
The SoC only composes the OSD and displays it.

**Comment by AlexandreBonneau** [comment]
Quick question since you emphasized `this`. ; Since I think this feature could still be very useful for the overall image quality, is this something that should be posted in a different repository in the HDZero organization?
Or is it out of HDZero's hand?
Thanks :>

**Comment by bkleiner** [comment]
Not directly on github, but divimath is known for incorporating community feedback.
Whether or not it is feasible with the current generation of hardware, i do not know.
I suspect if it were they would already have done something along those lines, it's a common complaint.

**Comment by francoisbeaussier** [comment]
Would love to know if someone had more info about the feasability of this.

New to all of this and after a few weeks of research, I really wanted to get into HDZero but recent reviews on youtube showcasing the random colour static have made me doubt myself.
