### ISSUE TITLE
Switching HDZERO channels while on analog

### ISSUE THREAD

**Issue by qvasic** [hd-zero/hdzero-goggle#400]
I have scroll wheel configured to change HDZERO channels.
But while I am flying analog, accidently rotating scroll wheel still asks "To R5?" Yet it is impossible to change analog channel (obviously) and it doesn't go to selected HDZERO channel, and there is apparently no way to dismiss the message, except going to menu and back.

I suggest either:
1. Do not show that message while on analog.
2. Show it, but go to chosen HDZERO channel when clicked.

In any case, this message should disappear after some timeout, even if shown while HDZERO channel is active.

**Comment by ligenxxxx** [comment]
It's a bug.
https://github.com/hd-zero/hdzero-goggle/pull/420
Please test this fw. https://github.com/hd-zero/hdzero-goggle/actions/runs/9394943200
