### ISSUE TITLE
Feature Request - Headtracking Data in OSD

### ISSUE THREAD

**Issue by Hexenschurtz** [hd-zero/hdzero-goggle#405]
Hi there,

I think I already read about this but in the facebook group noone could help about this:

I would love to be able to see the headtracking data in the OSD of the goggle to be able to judge better about my lost posure.
If thats already out somewhere please let me know and ignore this.
Thanks for all your work!

**Comment by ligenxxxx** [comment]
I thought this was worth adding.
The gyroscope data is part of the Goggle OSD, hidden by default, you can enable it in the OSD menu, and it even supports different display modes, such as graph, numeric.
