### ISSUE TITLE
FW file menu dont go away

### ISSUE THREAD

**Issue by lesharodin** [hd-zero/hdzero-goggle#410]
When you enter update menu and dont pick any file, this menu just wont close untill reboot 
![image](https://github.com/hd-zero/hdzero-goggle/assets/12091173/8c06b099-cfe0-44d0-aea5-e4979af6c072)

**Comment by SumolX** [comment]
I will look into this one.

**Comment by SumolX** [comment]
Please try this PR https://github.com/hd-zero/hdzero-goggle/pull/416 as I believe it's now fixed.  Tested on my setup.
