### ISSUE TITLE
Formatting SD card does not cause free space to be recalculated

### ISSUE THREAD

**Issue by evilC** [hd-zero/hdzero-goggle#412]
Seen on: 9.3.0-09eef33 rx:74 va:191
If the SD card is full, and you reformat the SD card, the SD card still shows as being full.
Rebooting causes free space to be recalculated, but this should not be required.
AFAIK a similar issue also applies if you delete recordings via the playback menu

**Comment by evilC** [comment]
Repro'd on this build: https://github.com/hd-zero/hdzero-goggle/actions/runs/9382157957
Test method:
1. FILL your SD card - on a windows system, for an SD card `F:`, in powershell:
```
cd F:
$space = $(get-WmiObject win32_logicaldisk | where-object -Property DeviceID -EQ "F:" | select -ExpandProperty FreeSpace) ; fsutil file createNew emptyFile $space
```
1. Put card in goggles - status bar shows "SD Card Full"
1. Storage menu > Format
1. Status bar still shows "SD Card Full"

**Comment by Master92** [comment]
Can you please try the artifact of [this build](https://github.com/Master92/hdzero-goggle/actions/runs/11775960009)?
I don't have my goggles at hand and therefore can't try it myself at the moment.

**Comment by evilC** [comment]
I just tried, but I cannot get the bloody SD card full :(
When I use the command I posted above, I get `Error:  There is not enough space on the disk.`  
Even if I format it and it's completely empty :(
