### ISSUE TITLE
Question: Which firmware is the most recent/most complete: Website vs. Github

### ISSUE THREAD

**Issue by HazzaHFPV** [hd-zero/hdzero-goggle#436]
Might be a stupid question but:

Website v9.4.0 vs. Github Main HDZERO_GOGGLE-75-191-**9.3.0**-7f34db8.bin

Does the firmware on the HDZero Website download section with v9.4.0 include all changes that the Github Main Version has, or is it "better"?

Currently I am using the above mentioned version from the "actions" page.
https://github.com/hd-zero/hdzero-goggle/actions/runs/10312492293
I am happy with this so far but.. Where are the differences to v9.4.0 on the Website?
Thank you.

**Comment by ligenxxxx** [comment]
Github is the most up to date. This also means it is less tested.
