### ISSUE TITLE
DVR with green bars

### ISSUE THREAD

**Issue by JohnnyCarvi** [hd-zero/hdzero-goggle#447]
Hi, after updating my HDZero goggles to the latest firmware version, sometimes the DVR recordings have green bars on the left and bottom sides, similar to the screen info. I'm using the Rev20240816 firmware. I never had this issue before. It happens with both analog and HDZero systems. 

![hdz_000](https://github.com/user-attachments/assets/04bc2271-6b51-4687-90c2-9d0e3fc10194)
[log.zip](https://github.com/user-attachments/files/17445118/log.zip)

**Comment by ligenxxxx** [comment]
Please refer https://github.com/hd-zero/hdzero-goggle/issues/432
