### ISSUE TITLE
Feature request: Update the goggles via the Wifi module

### ISSUE THREAD

**Issue by AlexandreBonneau** [hd-zero/hdzero-goggle#46]
It would be great to be able to ppdate the goggles firmware via the Wifi module.
One of the way would be to create a small localhost server on the goggle, that would serve a simple webpage where you could drop the zip or bin files to be flashed.

Also, that web server could display an information page with all the settings, versions, and configuration used.

**Comment by ligenxxxx** [comment]
solved.

**Comment by AlexandreBonneau** [comment]
@ligenxxxx Would you please have a link to the commit and/or updated documentation to see how to access such webserver à-la ExpressLRS?
