### ISSUE TITLE
Feature request: SSH to the goggles

### ISSUE THREAD

**Issue by AlexandreBonneau** [hd-zero/hdzero-goggle#47]
Well, knowing this is a Linux machine, I can't help but want to get access to the cmdline :>
Would it be possible in the future to ssh to the goggles via the Wifi module?

**Comment by a-di-ez** [comment]
awesome function for developers

**Comment by bkleiner** [comment]
its being worked on. SSH support should land with the release of the Wi-Fi hardware.

**Comment by a-di-ez** [comment]
thx, you are amazing!

**Comment by SumolX** [comment]
This is now in mainline and will be part of release 9.1

**Comment by ligenxxxx** [comment]
solved.
