### ISSUE TITLE
Feature request: Support for Bluetooth devices

### ISSUE THREAD

**Issue by AlexandreBonneau** [hd-zero/hdzero-goggle#49]
I'm not sure if this would be possible, but it would be great to have a way to add Bluetooth support to the goggles.
This way you could connect any type of devices (keyboard, mouse, microphones, gamepad, etc.) to the goggles.

**Comment by ligenxxxx** [comment]
ESP32 is occupied by backpack, and there is no plan to develop other functions for the time being.
