### ISSUE TITLE
BUG: Updating firmware resets Audio source setting

### ISSUE THREAD

**Issue by sabshire** [hd-zero/hdzero-goggle#58]
The source for the audio recording resets to default internal mic after updating firmware, instead of retaining user setting.

**Comment by bkleiner** [comment]
_all_ settings reset on firmware update as the settings file gets overwritten. i have looked into this and _for the time being_ this seems like our best bet to ensure files integrity and compatibility with the firmware.
If the settings interface changes down the line retaining settings on update can be re-visited.
