### ISSUE TITLE
Feature request: Option to show average cell voltage

### ISSUE THREAD

**Issue by evilC** [hd-zero/hdzero-goggle#68]
Please add an equivalent of BetaFlight's average cell voltage  
If you implemented #67 , then this would always be accurate-ish

ie, if (Once #67 is implemented) I have set the cell count set to 4S, and the current voltage of the pack is 12v, I want to see `3v` in the OSD for the voltage

**Comment by uPz3TT3r** [comment]
vote for this! 
+Add Voltage in overlay menü of all inputs (HDZero, Analog). So that its possible to react early on a race and change battery during heats, not only if warning comes up. (in my opinion voltage is more important info than fan speed of top fan)

**Comment by bkleiner** [comment]
i think both this and #67 are absolutely necessary features and should be implemented at the next juncture.
There is some "plumbing" work i would like to take care off first however.

**Comment by evilC** [comment]
> vote for this! +Add Voltage in overlay menü of all inputs (HDZero, Analog). So that its possible to react early on a race and change battery during heats, not only if warning comes up. (in my opinion voltage is more important info than fan speed of top fan)

I agree

**Comment by MartinHugh** [comment]
Just to be clear, if we are talking about displaying the "goggle" battery voltage, either total or cell - I dont mind, I think it is essential, and would very much welcome it.

**Comment by MartinHugh** [comment]
Is this supposed to show the voltage in the flight OSD, or in the menu.

I cant see it in the flight OSD.  Should I raise another issue for this ?

**Comment by bkleiner** [comment]
PR supplies the battery logic, but does not modify _where_ it is displayed, as the _orginial_ feature request stated.
So if you would like to see it be displayed somewhere else please raise a new request for that.

**Comment by MartinHugh** [comment]
> PR supplies the battery logic, but does not modify _where_ it is displayed, as the _orginial_ feature request stated. So if you would like to see it be displayed somewhere else please raise a new request for that.

Thanks
