### ISSUE TITLE
Fan control issue

### ISSUE THREAD

**Issue by adamg-86** [hd-zero/hdzero-goggle#76]
If the top fan is set to 0, when the goggle starts overheating the top fan goes to 5 but the side fans are not working and the manual control in the fan menu is not working when that happens. The result is the goggle keeps overheating until they are turned off. See video
https://www.youtube.com/watch?v=NaSG6zxUZBI

**Comment by rquellet** [comment]
Top fan minimum speed is now 1 of 5 in test fw

**Comment by bkleiner** [comment]
change landed on GH in https://github.com/hd-zero/hdzero-goggle/pull/79
