### ISSUE TITLE
HDMI audio out is not working.

### ISSUE THREAD

**Issue by SumolX** [hd-zero/hdzero-goggle#90]
During video playback via HDMI out, the audio portion is not being streamed.  While audio is working from the headphone jack, via HDMI out there is no sound.

I have investigated both DM5680 and IT66121 and the commands are cryptic as I do not have any reference development documentation.  Would anyone have a link to where I can download the SDK for these devices?

**Comment by ligenxxxx** [comment]
The audio from both HDMI IN and HDMI OUT is not connected.
