### ISSUE TITLE
When you format an SD Card, the text is "Formating" instead of "Formatting".

### ISSUE THREAD

**Issue by SuperSniper1018** [hd-zero/hdzero-goggle#91]
Obviously not high priority, but probably something to fix. 

To replicate, just put in an SD Card with a format other that exfat and go format it under Recording Options

**Comment by bkleiner** [comment]
has already been fixed, https://github.com/hd-zero/hdzero-goggle/commit/c0a3191ec17942dad6f3e9737499d9c0dbb94b89 should rollout with the next update.

**Comment by SuperSniper1018** [comment]
Wow that was fast lol. Alright, good to know it's fixed.
