### ISSUE TITLE
Feature Request: Delete all DVR files without formatting SD card

### ISSUE THREAD

**Issue by evilC** [hd-zero/hdzero-goggle#97]
While in the field, the only way (Obviously without removing the SD card and using another device) to clear out DVR files is to format the SD card.  
This will mean, for example, that any firmware files (And any custom boot screen logo?) that are stored on the SD card will be lost.  
An option should be added that clears out all the DVR files without deleting the rest of the contents of the SD card.

**Comment by ligenxxxx** [comment]
TODO
